server:
  port: 8181
  tomcat:
    uri-encoding: UTF-8
  session:
    timeout: 3600
  error:
    whitelabel:
      enabled: false
      
spring:
  application:
    name: zcp-portal
  output:
    ansi:
      enabled: always
  resources:
    chain:
      enabled: true
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
    template-resolver-order: 2
  http:
    encoding:
      charset: UTF-8 # the encoding of HTTP requests/responses
      enabled: true # enable http encoding support
      force: true # force the configured encoding

security:
  basic:
    enabled: false

logging:
  level:
    root: INFO 
    org.apache: INFO   
  config: classpath:config/logback-spring.xml
  file : local
  path : data/logs

props:
  appName: zcp-portal-stage
  keycloak:
    zcp:
      clientId: ${CLIENT_ID}
      clientSecret: ${CLIENT_SECRET}
      accessTokenUri: ${ACCESS_TOKEN_URI}
      userAuthorizationUri: ${USER_AUTHORIZATION_URI}
      redirectUri: ${REDIRECT_URI}
  iam:
    baseUrl: ${IAM_BASE_URI}
  alertmanager:
    baseUrl: ${ALERT_BASE_URI}
  dashboard:
    baseUrl: ${DASHBOARD_BASE_URI}
  uploadPath: /zcp/upload

    