apiVersion: v1
kind: ConfigMap
metadata:
  name: zcp-portal-ui-config
  namespace: zcp-system
data:
  SPRING_ACTIVE_PROFILE: stage
  CLIENT_ID: account
  ACCESS_TOKEN_URI: https://lawai-iam.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/token
  USER_AUTHORIZATION_URI: https://lawai-iam.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/auth
  REDIRECT_URI: https://lawai-console.cloudzcp.io/login
  IAM_BASE_URI: http://zcp-iam:80
  ALERT_BASE_URI: http://zcp-alertmanager:80
  DASHBOARD_BASE_URI: https://lawai-dashboard.cloudzcp.io